# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.update_user_has_roles_request import UpdateUserHasRolesRequest

class TestUpdateUserHasRolesRequest(unittest.TestCase):
    """UpdateUserHasRolesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserHasRolesRequest:
        """Test UpdateUserHasRolesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserHasRolesRequest`
        """
        model = UpdateUserHasRolesRequest()
        if include_optional:
            return UpdateUserHasRolesRequest(
                roles = gateway_api_sdk.models.update_user_has_roles_request_roles.update_user_has_roles_request_roles(
                    read = True, 
                    create = False, )
            )
        else:
            return UpdateUserHasRolesRequest(
        )
        """

    def testUpdateUserHasRolesRequest(self):
        """Test UpdateUserHasRolesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
