# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model2721b23c1df3b4e71706e4ab04f9b0a8_request import Model2721b23c1df3b4e71706e4ab04f9b0a8Request

class TestModel2721b23c1df3b4e71706e4ab04f9b0a8Request(unittest.TestCase):
    """Model2721b23c1df3b4e71706e4ab04f9b0a8Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model2721b23c1df3b4e71706e4ab04f9b0a8Request:
        """Test Model2721b23c1df3b4e71706e4ab04f9b0a8Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model2721b23c1df3b4e71706e4ab04f9b0a8Request`
        """
        model = Model2721b23c1df3b4e71706e4ab04f9b0a8Request()
        if include_optional:
            return Model2721b23c1df3b4e71706e4ab04f9b0a8Request(
                code = 'HDR_CATEGORY_AVAILABLE_UPON_REQUEST',
                label = 'Available upon request',
                valid_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                valid_until = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                definition = 'Access to the software ...',
                origin = 'HDR'
            )
        else:
            return Model2721b23c1df3b4e71706e4ab04f9b0a8Request(
                code = 'HDR_CATEGORY_AVAILABLE_UPON_REQUEST',
                label = 'Available upon request',
                valid_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                definition = 'Access to the software ...',
                origin = 'HDR',
        )
        """

    def testModel2721b23c1df3b4e71706e4ab04f9b0a8Request(self):
        """Test Model2721b23c1df3b4e71706e4ab04f9b0a8Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
