# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.f5f0b860854ee5a33ee3d4b5f8a6d2fc200_response import F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response

class TestF5f0b860854ee5a33ee3d4b5f8a6d2fc200Response(unittest.TestCase):
    """F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response:
        """Test F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response`
        """
        model = F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response()
        if include_optional:
            return F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response(
                message = '',
                data = [
                    gateway_api_sdk.models.type_category.TypeCategory(
                        id = 1, 
                        name = 'Analysis', 
                        description = 'Tools used for data analysis', 
                        enabled = True, 
                        created_at = '2024-01-15T10:30Z', 
                        updated_at = '2024-06-01T08:00Z', )
                    ]
            )
        else:
            return F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response(
        )
        """

    def testF5f0b860854ee5a33ee3d4b5f8a6d2fc200Response(self):
        """Test F5f0b860854ee5a33ee3d4b5f8a6d2fc200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
