# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.create_widget_request import CreateWidgetRequest

class TestCreateWidgetRequest(unittest.TestCase):
    """CreateWidgetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWidgetRequest:
        """Test CreateWidgetRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWidgetRequest`
        """
        model = CreateWidgetRequest()
        if include_optional:
            return CreateWidgetRequest(
                widget_name = 'A really nice name',
                size_width = 400,
                size_height = 300,
                unit = 'px',
                include_search_bar = True,
                include_cohort_link = False,
                keep_proportions = True,
                permitted_domains = ["example.com","example.org"],
                included_datasets = [1,2,3],
                included_data_uses = [10,11],
                included_scripts = [5,6],
                included_collections = [99,100],
                data_custodian_entities_ids = [99,100]
            )
        else:
            return CreateWidgetRequest(
                widget_name = 'A really nice name',
        )
        """

    def testCreateWidgetRequest(self):
        """Test CreateWidgetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
