# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.search_data_custodian_networks_api import SearchDataCustodianNetworksApi


class TestSearchDataCustodianNetworksApi(unittest.TestCase):
    """SearchDataCustodianNetworksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchDataCustodianNetworksApi()

    def tearDown(self) -> None:
        pass

    def test_call_9b95892cc29cee3ccd11e3f92223224c(self) -> None:
        """Test case for call_9b95892cc29cee3ccd11e3f92223224c

        Search@data_custodian_networks
        """
        pass


if __name__ == '__main__':
    unittest.main()
