# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model3c8adeb001330f5198ca1072be78e299_request import Model3c8adeb001330f5198ca1072be78e299Request

class TestModel3c8adeb001330f5198ca1072be78e299Request(unittest.TestCase):
    """Model3c8adeb001330f5198ca1072be78e299Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model3c8adeb001330f5198ca1072be78e299Request:
        """Test Model3c8adeb001330f5198ca1072be78e299Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model3c8adeb001330f5198ca1072be78e299Request`
        """
        model = Model3c8adeb001330f5198ca1072be78e299Request()
        if include_optional:
            return Model3c8adeb001330f5198ca1072be78e299Request(
                name = 'Corrupti in a voluptas. Eligendi saepe sed sit.',
                image_link = 'https://via.placeholder.com/640x480.png/0022dd?text=animals+aliquam',
                description = 'Praesentium ut et quae suscipit ut quo adipisci. Enim ut tenetur ad omnis ut consequatur. ',
                team_id = 1,
                user_id = 2,
                enabled = False,
                permissions = [],
                notifications = []
            )
        else:
            return Model3c8adeb001330f5198ca1072be78e299Request(
                name = 'Corrupti in a voluptas. Eligendi saepe sed sit.',
                image_link = 'https://via.placeholder.com/640x480.png/0022dd?text=animals+aliquam',
                description = 'Praesentium ut et quae suscipit ut quo adipisci. Enim ut tenetur ad omnis ut consequatur. ',
                team_id = 1,
                user_id = 2,
                enabled = False,
                permissions = [],
        )
        """

    def testModel3c8adeb001330f5198ca1072be78e299Request(self):
        """Test Model3c8adeb001330f5198ca1072be78e299Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
