# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.search_tools_api import SearchToolsApi


class TestSearchToolsApi(unittest.TestCase):
    """SearchToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchToolsApi()

    def tearDown(self) -> None:
        pass

    def test_a3e02b5a05b56708998c4bd96935d5f5(self) -> None:
        """Test case for a3e02b5a05b56708998c4bd96935d5f5

        Search@tools
        """
        pass


if __name__ == '__main__':
    unittest.main()
