# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.d59dbdaa4244200f6b9060e166e337d9200_response import D59dbdaa4244200f6b9060e166e337d9200Response

class TestD59dbdaa4244200f6b9060e166e337d9200Response(unittest.TestCase):
    """D59dbdaa4244200f6b9060e166e337d9200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> D59dbdaa4244200f6b9060e166e337d9200Response:
        """Test D59dbdaa4244200f6b9060e166e337d9200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `D59dbdaa4244200f6b9060e166e337d9200Response`
        """
        model = D59dbdaa4244200f6b9060e166e337d9200Response()
        if include_optional:
            return D59dbdaa4244200f6b9060e166e337d9200Response(
                message = '',
                data = [
                    gateway_api_sdk.models.keyword.Keyword(
                        id = 1, 
                        name = 'genomics', 
                        enabled = True, 
                        created_at = '2024-01-15T10:30Z', 
                        updated_at = '2024-06-01T08:00Z', )
                    ],
                first_page_url = 'http:\/\/localhost:8000\/api\/v1\/keywords?page=1',
                var_from = 1,
                last_page = 1,
                last_page_url = 'http:\/\/localhost:8000\/api\/v1\/keywords?page=1',
                links = [],
                next_page_url = 'null',
                path = 'http:\/\/localhost:8000\/api\/v1\/keywords',
                per_page = 25,
                prev_page_url = 'null',
                to = 3,
                total = 3
            )
        else:
            return D59dbdaa4244200f6b9060e166e337d9200Response(
        )
        """

    def testD59dbdaa4244200f6b9060e166e337d9200Response(self):
        """Test D59dbdaa4244200f6b9060e166e337d9200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
