# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model473ee45c3962ae2a02abbac5015dce6a200_response import Model473ee45c3962ae2a02abbac5015dce6a200Response

class TestModel473ee45c3962ae2a02abbac5015dce6a200Response(unittest.TestCase):
    """Model473ee45c3962ae2a02abbac5015dce6a200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model473ee45c3962ae2a02abbac5015dce6a200Response:
        """Test Model473ee45c3962ae2a02abbac5015dce6a200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model473ee45c3962ae2a02abbac5015dce6a200Response`
        """
        model = Model473ee45c3962ae2a02abbac5015dce6a200Response()
        if include_optional:
            return Model473ee45c3962ae2a02abbac5015dce6a200Response(
                message = '',
                data = gateway_api_sdk.models._473ee45c3962ae2a02abbac5015dce6a_200_response_data._473ee45c3962ae2a02abbac5015dce6a_200_response_data(
                    id = 123, 
                    answers = [
                        null
                        ], )
            )
        else:
            return Model473ee45c3962ae2a02abbac5015dce6a200Response(
        )
        """

    def testModel473ee45c3962ae2a02abbac5015dce6a200Response(self):
        """Test Model473ee45c3962ae2a02abbac5015dce6a200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
