# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.create_enquiry_threads_request import CreateEnquiryThreadsRequest

class TestCreateEnquiryThreadsRequest(unittest.TestCase):
    """CreateEnquiryThreadsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEnquiryThreadsRequest:
        """Test CreateEnquiryThreadsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEnquiryThreadsRequest`
        """
        model = CreateEnquiryThreadsRequest()
        if include_optional:
            return CreateEnquiryThreadsRequest(
                user_id = 123,
                project_title = 'Project Title',
                is_dar_dialogue = False,
                is_dar_status = False,
                is_feasibility_enquiry = False,
                is_general_enquiry = False,
                is_dar_review = False,
                enabled = True
            )
        else:
            return CreateEnquiryThreadsRequest(
                user_id = 123,
                project_title = 'Project Title',
        )
        """

    def testCreateEnquiryThreadsRequest(self):
        """Test CreateEnquiryThreadsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
