# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.create_notifications_request import CreateNotificationsRequest

class TestCreateNotificationsRequest(unittest.TestCase):
    """CreateNotificationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNotificationsRequest:
        """Test CreateNotificationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNotificationsRequest`
        """
        model = CreateNotificationsRequest()
        if include_optional:
            return CreateNotificationsRequest(
                notification_type = 'applicationSubmitted',
                message = 'your message here',
                opt_in = False,
                enabled = False,
                email = 'john@example.com'
            )
        else:
            return CreateNotificationsRequest(
                notification_type = 'applicationSubmitted',
                message = 'your message here',
                opt_in = False,
                enabled = False,
        )
        """

    def testCreateNotificationsRequest(self):
        """Test CreateNotificationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
