# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model1fd84d2c66035574da4902f416cbd96a_request import Model1fd84d2c66035574da4902f416cbd96aRequest

class TestModel1fd84d2c66035574da4902f416cbd96aRequest(unittest.TestCase):
    """Model1fd84d2c66035574da4902f416cbd96aRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model1fd84d2c66035574da4902f416cbd96aRequest:
        """Test Model1fd84d2c66035574da4902f416cbd96aRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model1fd84d2c66035574da4902f416cbd96aRequest`
        """
        model = Model1fd84d2c66035574da4902f416cbd96aRequest()
        if include_optional:
            return Model1fd84d2c66035574da4902f416cbd96aRequest(
                notification_type = 'applicationSubmitted',
                message = 'your message here',
                opt_in = False,
                enabled = False,
                email = 'john@example.com'
            )
        else:
            return Model1fd84d2c66035574da4902f416cbd96aRequest(
                notification_type = 'applicationSubmitted',
                message = 'your message here',
                opt_in = False,
                enabled = False,
        )
        """

    def testModel1fd84d2c66035574da4902f416cbd96aRequest(self):
        """Test Model1fd84d2c66035574da4902f416cbd96aRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
