# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model9b95892cc29cee3ccd11e3f92223224c200_response_data_inner_source_inner import Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner

class TestModel9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner(unittest.TestCase):
    """Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner:
        """Test Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner`
        """
        model = Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner()
        if include_optional:
            return Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner(
                id = '',
                name = '',
                img_url = '',
                dataset_titles = [
                    null
                    ],
                geographic_location = [
                    null
                    ]
            )
        else:
            return Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner(
        )
        """

    def testModel9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner(self):
        """Test Model9b95892cc29cee3ccd11e3f92223224c200ResponseDataInnerSourceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
