# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.saved_search_api import SavedSearchApi


class TestSavedSearchApi(unittest.TestCase):
    """SavedSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SavedSearchApi()

    def tearDown(self) -> None:
        pass

    def test_call_39500344ecf1a14150bbe26c4a138c56(self) -> None:
        """Test case for call_39500344ecf1a14150bbe26c4a138c56

        SavedSearch@store
        """
        pass

    def test_call_3b59d921ea47286a669054ef67350b03(self) -> None:
        """Test case for call_3b59d921ea47286a669054ef67350b03

        SavedSearch@update
        """
        pass

    def test_call_4f2a3c56631a5fccb45a9e7972df02b0(self) -> None:
        """Test case for call_4f2a3c56631a5fccb45a9e7972df02b0

        SavedSearch@index
        """
        pass

    def test_call_8d6878e4937dd67c5e2480c6f4e9149f(self) -> None:
        """Test case for call_8d6878e4937dd67c5e2480c6f4e9149f

        SavedSearch@show
        """
        pass

    def test_cdcdceead49fe1554534af83c50c8af5(self) -> None:
        """Test case for cdcdceead49fe1554534af83c50c8af5

        SavedSearch@destroy
        """
        pass

    def test_fa314398c7a73002fee4ffc7e62e9fb6(self) -> None:
        """Test case for fa314398c7a73002fee4ffc7e62e9fb6

        SavedSearch@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
