# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.update_question_bank_question200_response import UpdateQuestionBankQuestion200Response

class TestUpdateQuestionBankQuestion200Response(unittest.TestCase):
    """UpdateQuestionBankQuestion200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateQuestionBankQuestion200Response:
        """Test UpdateQuestionBankQuestion200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateQuestionBankQuestion200Response`
        """
        model = UpdateQuestionBankQuestion200Response()
        if include_optional:
            return UpdateQuestionBankQuestion200Response(
                message = '',
                data = gateway_api_sdk.models.question_bank.QuestionBank(
                    id = 1, 
                    section_id = 3, 
                    user_id = 42, 
                    locked = False, 
                    archived = False, 
                    archived_date = '2024-06-01T08:00Z', 
                    force_required = False, 
                    allow_guidance_override = False, 
                    is_child = False, 
                    question_type = 'STANDARD', 
                    created_at = '2024-01-15T10:30Z', 
                    updated_at = '2024-06-01T08:00Z', )
            )
        else:
            return UpdateQuestionBankQuestion200Response(
        )
        """

    def testUpdateQuestionBankQuestion200Response(self):
        """Test UpdateQuestionBankQuestion200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
