# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.create_applications200_response_data_inner import CreateApplications200ResponseDataInner

class TestCreateApplications200ResponseDataInner(unittest.TestCase):
    """CreateApplications200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateApplications200ResponseDataInner:
        """Test CreateApplications200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApplications200ResponseDataInner`
        """
        model = CreateApplications200ResponseDataInner()
        if include_optional:
            return CreateApplications200ResponseDataInner(
                id = 123,
                name = 'Voluptas incidunt repellat animi. Sed ut beatae fugit ullam.',
                app_id = 'obmWCcsccdxH5iHgLTJDZNXNkyW1ZxZ3',
                client_id = 'w8CLyeP8vhnPK1V0mJ8ubU7UHCVnK7Bm',
                client_secret = 'w8CLyeP8vhnPK1V0mJ8ubU7UHCVnK7Bm',
                image_link = 'hhttps:\/\/via.placeholder.com\/640x480.png\/0044ee?text=animals+harum',
                description = 'Magni minima facilis quo soluta. Ab quasi quaerat doloremque. Sapiente asperiores nisi maiores ex quia velit.',
                team_id = 1,
                user_id = 2,
                enabled = False,
                permissions = [],
                team = [],
                user = [],
                notifications = [],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreateApplications200ResponseDataInner(
        )
        """

    def testCreateApplications200ResponseDataInner(self):
        """Test CreateApplications200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
