# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.alias_controller_index200_response import AliasControllerIndex200Response

class TestAliasControllerIndex200Response(unittest.TestCase):
    """AliasControllerIndex200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AliasControllerIndex200Response:
        """Test AliasControllerIndex200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AliasControllerIndex200Response`
        """
        model = AliasControllerIndex200Response()
        if include_optional:
            return AliasControllerIndex200Response(
                message = '',
                data = [
                    gateway_api_sdk.models.alias.Alias(
                        id = 1, 
                        name = 'Also known as XYZ', )
                    ]
            )
        else:
            return AliasControllerIndex200Response(
        )
        """

    def testAliasControllerIndex200Response(self):
        """Test AliasControllerIndex200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
