# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.edit_csat200_response import EditCsat200Response

class TestEditCsat200Response(unittest.TestCase):
    """EditCsat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditCsat200Response:
        """Test EditCsat200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditCsat200Response`
        """
        model = EditCsat200Response()
        if include_optional:
            return EditCsat200Response(
                message = 'reason updated'
            )
        else:
            return EditCsat200Response(
        )
        """

    def testEditCsat200Response(self):
        """Test EditCsat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
