# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model3b69b09a466561df872e104a19a2ad65200_response_data import Model3b69b09a466561df872e104a19a2ad65200ResponseData

class TestModel3b69b09a466561df872e104a19a2ad65200ResponseData(unittest.TestCase):
    """Model3b69b09a466561df872e104a19a2ad65200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model3b69b09a466561df872e104a19a2ad65200ResponseData:
        """Test Model3b69b09a466561df872e104a19a2ad65200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model3b69b09a466561df872e104a19a2ad65200ResponseData`
        """
        model = Model3b69b09a466561df872e104a19a2ad65200ResponseData()
        if include_optional:
            return Model3b69b09a466561df872e104a19a2ad65200ResponseData(
                id = 1,
                datasets = {},
                datasets_total = 1
            )
        else:
            return Model3b69b09a466561df872e104a19a2ad65200ResponseData(
        )
        """

    def testModel3b69b09a466561df872e104a19a2ad65200ResponseData(self):
        """Test Model3b69b09a466561df872e104a19a2ad65200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
