# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.b42015102cb75735f63c91ed0c89aadc200_response_data import B42015102cb75735f63c91ed0c89aadc200ResponseData

class TestB42015102cb75735f63c91ed0c89aadc200ResponseData(unittest.TestCase):
    """B42015102cb75735f63c91ed0c89aadc200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> B42015102cb75735f63c91ed0c89aadc200ResponseData:
        """Test B42015102cb75735f63c91ed0c89aadc200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `B42015102cb75735f63c91ed0c89aadc200ResponseData`
        """
        model = B42015102cb75735f63c91ed0c89aadc200ResponseData()
        if include_optional:
            return B42015102cb75735f63c91ed0c89aadc200ResponseData(
                id = 1,
                durs_total = 1,
                durs = {},
                tools_total = 1,
                tools = {},
                publications_total = 1,
                publications = {},
                collections_total = 1,
                collections = {}
            )
        else:
            return B42015102cb75735f63c91ed0c89aadc200ResponseData(
        )
        """

    def testB42015102cb75735f63c91ed0c89aadc200ResponseData(self):
        """Test B42015102cb75735f63c91ed0c89aadc200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
