# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model3b59d921ea47286a669054ef67350b03_request import Model3b59d921ea47286a669054ef67350b03Request

class TestModel3b59d921ea47286a669054ef67350b03Request(unittest.TestCase):
    """Model3b59d921ea47286a669054ef67350b03Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model3b59d921ea47286a669054ef67350b03Request:
        """Test Model3b59d921ea47286a669054ef67350b03Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model3b59d921ea47286a669054ef67350b03Request`
        """
        model = Model3b59d921ea47286a669054ef67350b03Request()
        if include_optional:
            return Model3b59d921ea47286a669054ef67350b03Request(
                name = 'Name',
                search_endpoint = 'datasets',
                filters = [
                    gateway_api_sdk.models._39500344ecf1a14150bbe26c4a138c56_request_filters_inner._39500344ecf1a14150bbe26c4a138c56_request_filters_inner(
                        id = 1, 
                        terms = ['A publisher'], )
                    ],
                enabled = 'true'
            )
        else:
            return Model3b59d921ea47286a669054ef67350b03Request(
                name = 'Name',
                enabled = 'true',
        )
        """

    def testModel3b59d921ea47286a669054ef67350b03Request(self):
        """Test Model3b59d921ea47286a669054ef67350b03Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
