# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.upload_api import UploadApi


class TestUploadApi(unittest.TestCase):
    """UploadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadApi()

    def tearDown(self) -> None:
        pass

    def test_ba8ab1a2710efebacb7909736d7d2d52(self) -> None:
        """Test case for ba8ab1a2710efebacb7909736d7d2d52

        Upload@destroy
        """
        pass

    def test_call_21a780f609f0b91c198ab5de91dc27c6(self) -> None:
        """Test case for call_21a780f609f0b91c198ab5de91dc27c6

        Upload@content
        """
        pass

    def test_e72aa4b4f0a80caa9fe872bdff983455(self) -> None:
        """Test case for e72aa4b4f0a80caa9fe872bdff983455

        Upload@show
        """
        pass

    def test_fceeda218a8998a137b9d7692e7947b6(self) -> None:
        """Test case for fceeda218a8998a137b9d7692e7947b6

        Upload@upload
        """
        pass


if __name__ == '__main__':
    unittest.main()
