# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.team_federations_api import TeamFederationsApi


class TestTeamFederationsApi(unittest.TestCase):
    """TeamFederationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamFederationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_federation_team(self) -> None:
        """Test case for create_federation_team

        FederationController@store
        """
        pass

    def test_delete_federation(self) -> None:
        """Test case for delete_federation

        FederationController@destroy
        """
        pass

    def test_edit_federation_team(self) -> None:
        """Test case for edit_federation_team

        FederationController@edit
        """
        pass

    def test_get_federation_by_federation_id_and_team_id(self) -> None:
        """Test case for get_federation_by_federation_id_and_team_id

        FederationController@show
        """
        pass

    def test_get_federation_history(self) -> None:
        """Test case for get_federation_history

        FederationController@history
        """
        pass

    def test_get_federation_team_id(self) -> None:
        """Test case for get_federation_team_id

        FederationController@index
        """
        pass

    def test_run_federation(self) -> None:
        """Test case for run_federation

        FederationController@runNow
        """
        pass

    def test_test_federation(self) -> None:
        """Test case for test_federation

        FederationController@testFederation
        """
        pass

    def test_update_federation_team(self) -> None:
        """Test case for update_federation_team

        FederationController@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
