# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.cd41e1bd1b9f9918da2bb53a240b8bfe200_response_data_inner import Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner

class TestCd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner(unittest.TestCase):
    """Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner:
        """Test Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner`
        """
        model = Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner()
        if include_optional:
            return Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner(
                source = [
                    gateway_api_sdk.models.b60e5c6bd58001740003449e91216454_200_response_data_inner__source_inner.b60e5c6bd58001740003449e91216454_200_response_data_inner__source_inner(
                        abstract = '', 
                        description = '', 
                        keywords = '', 
                        named_entities = [
                            null
                            ], 
                        publisher_name = '', 
                        short_title = '', 
                        title = '', 
                        created_at = '', )
                    ],
                metadata = [
                    null
                    ]
            )
        else:
            return Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner(
        )
        """

    def testCd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner(self):
        """Test Cd41e1bd1b9f9918da2bb53a240b8bfe200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
