# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model7f39b24417648f048a9457326619439c_request import Model7f39b24417648f048a9457326619439cRequest

class TestModel7f39b24417648f048a9457326619439cRequest(unittest.TestCase):
    """Model7f39b24417648f048a9457326619439cRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model7f39b24417648f048a9457326619439cRequest:
        """Test Model7f39b24417648f048a9457326619439cRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model7f39b24417648f048a9457326619439cRequest`
        """
        model = Model7f39b24417648f048a9457326619439cRequest()
        if include_optional:
            return Model7f39b24417648f048a9457326619439cRequest(
                min_id = 56,
                max_id = 56
            )
        else:
            return Model7f39b24417648f048a9457326619439cRequest(
        )
        """

    def testModel7f39b24417648f048a9457326619439cRequest(self):
        """Test Model7f39b24417648f048a9457326619439cRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
