# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model70d4b0fcc281e6491f510f58028762c9_request import Model70d4b0fcc281e6491f510f58028762c9Request

class TestModel70d4b0fcc281e6491f510f58028762c9Request(unittest.TestCase):
    """Model70d4b0fcc281e6491f510f58028762c9Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model70d4b0fcc281e6491f510f58028762c9Request:
        """Test Model70d4b0fcc281e6491f510f58028762c9Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model70d4b0fcc281e6491f510f58028762c9Request`
        """
        model = Model70d4b0fcc281e6491f510f58028762c9Request()
        if include_optional:
            return Model70d4b0fcc281e6491f510f58028762c9Request(
                team_id = 1,
                user_id = 1,
                published = True,
                locked = False,
                questions = [
                    gateway_api_sdk.models._70d4b0fcc281e6491f510f58028762c9_request_questions_inner._70d4b0fcc281e6491f510f58028762c9_request_questions_inner(
                        id = 1, 
                        guidance = 'Custom guidance', 
                        required = True, 
                        order = 1, )
                    ]
            )
        else:
            return Model70d4b0fcc281e6491f510f58028762c9Request(
                team_id = 1,
        )
        """

    def testModel70d4b0fcc281e6491f510f58028762c9Request(self):
        """Test Model70d4b0fcc281e6491f510f58028762c9Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
