# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.ced8add57941554cde6a5fc53f6555e5200_response_data import Ced8add57941554cde6a5fc53f6555e5200ResponseData

class TestCed8add57941554cde6a5fc53f6555e5200ResponseData(unittest.TestCase):
    """Ced8add57941554cde6a5fc53f6555e5200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ced8add57941554cde6a5fc53f6555e5200ResponseData:
        """Test Ced8add57941554cde6a5fc53f6555e5200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ced8add57941554cde6a5fc53f6555e5200ResponseData`
        """
        model = Ced8add57941554cde6a5fc53f6555e5200ResponseData()
        if include_optional:
            return Ced8add57941554cde6a5fc53f6555e5200ResponseData(
                id = 1,
                teams_counts = {}
            )
        else:
            return Ced8add57941554cde6a5fc53f6555e5200ResponseData(
        )
        """

    def testCed8add57941554cde6a5fc53f6555e5200ResponseData(self):
        """Test Ced8add57941554cde6a5fc53f6555e5200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
