# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.license_api import LicenseApi


class TestLicenseApi(unittest.TestCase):
    """LicenseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LicenseApi()

    def tearDown(self) -> None:
        pass

    def test_create_licenses(self) -> None:
        """Test case for create_licenses

        License@store
        """
        pass

    def test_delete_licenses(self) -> None:
        """Test case for delete_licenses

        License@destroy
        """
        pass

    def test_edit_licenses(self) -> None:
        """Test case for edit_licenses

        License@edit
        """
        pass

    def test_fetch_all_licenses(self) -> None:
        """Test case for fetch_all_licenses

        License@index
        """
        pass

    def test_fetch_licenses(self) -> None:
        """Test case for fetch_licenses

        License@show
        """
        pass

    def test_update_licenses(self) -> None:
        """Test case for update_licenses

        License@update
        """
        pass


if __name__ == '__main__':
    unittest.main()
