# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.search_datasets200_response_data_inner_source_inner import SearchDatasets200ResponseDataInnerSourceInner

class TestSearchDatasets200ResponseDataInnerSourceInner(unittest.TestCase):
    """SearchDatasets200ResponseDataInnerSourceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchDatasets200ResponseDataInnerSourceInner:
        """Test SearchDatasets200ResponseDataInnerSourceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchDatasets200ResponseDataInnerSourceInner`
        """
        model = SearchDatasets200ResponseDataInnerSourceInner()
        if include_optional:
            return SearchDatasets200ResponseDataInnerSourceInner(
                abstract = '',
                description = '',
                keywords = '',
                named_entities = [
                    null
                    ],
                publisher_name = '',
                short_title = '',
                title = '',
                created_at = ''
            )
        else:
            return SearchDatasets200ResponseDataInnerSourceInner(
        )
        """

    def testSearchDatasets200ResponseDataInnerSourceInner(self):
        """Test SearchDatasets200ResponseDataInnerSourceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
