# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.fetch_dashboard_download_csv_v3500_response import FetchDashboardDownloadCsvV3500Response

class TestFetchDashboardDownloadCsvV3500Response(unittest.TestCase):
    """FetchDashboardDownloadCsvV3500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchDashboardDownloadCsvV3500Response:
        """Test FetchDashboardDownloadCsvV3500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchDashboardDownloadCsvV3500Response`
        """
        model = FetchDashboardDownloadCsvV3500Response()
        if include_optional:
            return FetchDashboardDownloadCsvV3500Response(
                message = 'error',
                data = 'startDate must be less than or equal to endDate'
            )
        else:
            return FetchDashboardDownloadCsvV3500Response(
        )
        """

    def testFetchDashboardDownloadCsvV3500Response(self):
        """Test FetchDashboardDownloadCsvV3500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
