# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.data_use_registers_api import DataUseRegistersApi


class TestDataUseRegistersApi(unittest.TestCase):
    """DataUseRegistersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataUseRegistersApi()

    def tearDown(self) -> None:
        pass

    def test_call_220a00f946309dea9f126baed550c9cd(self) -> None:
        """Test case for call_220a00f946309dea9f126baed550c9cd

        DurController@exportTemplate
        """
        pass

    def test_call_2c16b33b0f6636db91657b64f4a7bbda(self) -> None:
        """Test case for call_2c16b33b0f6636db91657b64f4a7bbda

        Update a dur by id
        """
        pass

    def test_call_3d9acaab46169ca5e55cf017e9659f8e(self) -> None:
        """Test case for call_3d9acaab46169ca5e55cf017e9659f8e

        Edit a dur
        """
        pass

    def test_call_491cd8b54449d3269b5d69d4d5732523(self) -> None:
        """Test case for call_491cd8b54449d3269b5d69d4d5732523

        DurController@exportTemplate
        """
        pass

    def test_count_team_unique_fields_dur_v2(self) -> None:
        """Test case for count_team_unique_fields_dur_v2

        TeamDurController@count
        """
        pass

    def test_create_dur(self) -> None:
        """Test case for create_dur

        DurController@store
        """
        pass

    def test_create_dur_by_team_v2(self) -> None:
        """Test case for create_dur_by_team_v2

        TeamDurController@store
        """
        pass

    def test_delete_durs_v2_by_team_id(self) -> None:
        """Test case for delete_durs_v2_by_team_id

        TeamDurController@destroy
        """
        pass

    def test_e78bbbfec43b70397fd580225bb968ce(self) -> None:
        """Test case for e78bbbfec43b70397fd580225bb968ce

        Delete a dur
        """
        pass

    def test_edit_durs_v2_by_team_id(self) -> None:
        """Test case for edit_durs_v2_by_team_id

        TeamDurController@edit
        """
        pass

    def test_export_dur_v2(self) -> None:
        """Test case for export_dur_v2

        DurController@export
        """
        pass

    def test_fetch_all_dur(self) -> None:
        """Test case for fetch_all_dur

        DurController@index
        """
        pass

    def test_fetch_all_dur_v2(self) -> None:
        """Test case for fetch_all_dur_v2

        DurController@indexActive
        """
        pass

    def test_fetch_all_team_dur_status(self) -> None:
        """Test case for fetch_all_team_dur_status

        TeamDurController@indexStatus
        """
        pass

    def test_fetch_dur_by_id(self) -> None:
        """Test case for fetch_dur_by_id

        DurController@show
        """
        pass

    def test_fetch_dur_by_id_v2(self) -> None:
        """Test case for fetch_dur_by_id_v2

        DurController@showActive
        """
        pass

    def test_fetch_dur_by_team_and_by_id_v2(self) -> None:
        """Test case for fetch_dur_by_team_and_by_id_v2

        TeamDurController@show
        """
        pass

    def test_update_dur_v2_by_team_id(self) -> None:
        """Test case for update_dur_v2_by_team_id

        TeamDurController@update
        """
        pass

    def test_upload_dur(self) -> None:
        """Test case for upload_dur

        DurController@upload
        """
        pass


if __name__ == '__main__':
    unittest.main()
