# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.fetch_all_dur200_response import FetchAllDur200Response

class TestFetchAllDur200Response(unittest.TestCase):
    """FetchAllDur200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchAllDur200Response:
        """Test FetchAllDur200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchAllDur200Response`
        """
        model = FetchAllDur200Response()
        if include_optional:
            return FetchAllDur200Response(
                message = '',
                data = [
                    gateway_api_sdk.models.dur.Dur(
                        id = 88, 
                        project_title = 'COVID-19 outcomes study', 
                        project_id_text = '', 
                        organisation_name = 'NHS England', 
                        organisation_sector = '', 
                        sector_id = 56, 
                        lay_summary = '', 
                        technical_summary = '', 
                        latest_approval_date = 'Sat Jul 01 00:00:00 UTC 2023', 
                        manual_upload = False, 
                        rejection_reason = '', 
                        sublicence_arrangements = '', 
                        public_benefit_statement = '', 
                        data_sensitivity_level = '', 
                        project_start_date = 'Sun Jan 01 00:00:00 UTC 2023', 
                        project_end_date = 'Wed Dec 31 00:00:00 UTC 2025', 
                        access_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        accredited_researcher_status = '', 
                        confidential_data_description = '', 
                        dataset_linkage_description = '', 
                        duty_of_confidentiality = '', 
                        legal_basis_for_data_article6 = '', 
                        legal_basis_for_data_article9 = '', 
                        national_data_optout = '', 
                        organisation_id = '', 
                        privacy_enhancements = '', 
                        request_category_type = '', 
                        request_frequency = '', 
                        access_type = '', 
                        non_gateway_datasets = [
                            ''
                            ], 
                        non_gateway_applicants = [
                            ''
                            ], 
                        funders_and_sponsors = [
                            ''
                            ], 
                        other_approval_committees = [
                            ''
                            ], 
                        gateway_outputs_tools = [
                            ''
                            ], 
                        gateway_outputs_papers = [
                            ''
                            ], 
                        non_gateway_outputs = [
                            ''
                            ], 
                        enabled = True, 
                        last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        counter = 0, 
                        user_id = 56, 
                        team_id = 56, 
                        applicant_id = 56, 
                        status = 'ACTIVE', 
                        created_at = '2024-01-15T10:30Z', 
                        updated_at = '2024-06-01T08:00Z', )
                    ],
                first_page_url = 'http:\/\/localhost:8000\/api\/v1\/collections?page=1',
                var_from = 1,
                last_page = 1,
                last_page_url = 'http:\/\/localhost:8000\/api\/v1\/collections?page=1',
                links = [],
                next_page_url = 'null',
                path = 'http:\/\/localhost:8000\/api\/v1\/collections',
                per_page = 25,
                prev_page_url = 'null',
                to = 3,
                total = 3
            )
        else:
            return FetchAllDur200Response(
        )
        """

    def testFetchAllDur200Response(self):
        """Test FetchAllDur200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
