# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.a961db529080eb3a29e4b7cc13dabaaa_request import A961db529080eb3a29e4b7cc13dabaaaRequest

class TestA961db529080eb3a29e4b7cc13dabaaaRequest(unittest.TestCase):
    """A961db529080eb3a29e4b7cc13dabaaaRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> A961db529080eb3a29e4b7cc13dabaaaRequest:
        """Test A961db529080eb3a29e4b7cc13dabaaaRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `A961db529080eb3a29e4b7cc13dabaaaRequest`
        """
        model = A961db529080eb3a29e4b7cc13dabaaaRequest()
        if include_optional:
            return A961db529080eb3a29e4b7cc13dabaaaRequest(
                user_id = 123,
                project_title = 'Project Title',
                is_dar_dialogue = False,
                is_dar_status = False,
                is_feasibility_enquiry = False,
                is_general_enquiry = False,
                is_dar_review = False,
                enabled = True
            )
        else:
            return A961db529080eb3a29e4b7cc13dabaaaRequest(
                user_id = 123,
                project_title = 'Project Title',
        )
        """

    def testA961db529080eb3a29e4b7cc13dabaaaRequest(self):
        """Test A961db529080eb3a29e4b7cc13dabaaaRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
