# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model94f1c18e47daa32c1346be4a0d0449e4200_response import Model94f1c18e47daa32c1346be4a0d0449e4200Response

class TestModel94f1c18e47daa32c1346be4a0d0449e4200Response(unittest.TestCase):
    """Model94f1c18e47daa32c1346be4a0d0449e4200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model94f1c18e47daa32c1346be4a0d0449e4200Response:
        """Test Model94f1c18e47daa32c1346be4a0d0449e4200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model94f1c18e47daa32c1346be4a0d0449e4200Response`
        """
        model = Model94f1c18e47daa32c1346be4a0d0449e4200Response()
        if include_optional:
            return Model94f1c18e47daa32c1346be4a0d0449e4200Response(
                message = '',
                data = [
                    gateway_api_sdk.models._94f1c18e47daa32c1346be4a0d0449e4_200_response_data_inner._94f1c18e47daa32c1346be4a0d0449e4_200_response_data_inner(
                        id = 123, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = 'Safe People', 
                        description = 'Who has access?', 
                        parent_section = 1, 
                        order = 1, )
                    ]
            )
        else:
            return Model94f1c18e47daa32c1346be4a0d0449e4200Response(
        )
        """

    def testModel94f1c18e47daa32c1346be4a0d0449e4200Response(self):
        """Test Model94f1c18e47daa32c1346be4a0d0449e4200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
