# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.reviews_api import ReviewsApi


class TestReviewsApi(unittest.TestCase):
    """ReviewsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReviewsApi()

    def tearDown(self) -> None:
        pass

    def test_call_205dc23d44b18ca0b5c26a293cc69cf7(self) -> None:
        """Test case for call_205dc23d44b18ca0b5c26a293cc69cf7

        Delete a review
        """
        pass

    def test_call_31ad2467e98e52298b4e39e2741447f1(self) -> None:
        """Test case for call_31ad2467e98e52298b4e39e2741447f1

        Edit a review
        """
        pass

    def test_call_64b4b952592ebe8e0b00204e76bd991c(self) -> None:
        """Test case for call_64b4b952592ebe8e0b00204e76bd991c

        Update a review
        """
        pass

    def test_create_reviews(self) -> None:
        """Test case for create_reviews

        ReviewController@store
        """
        pass

    def test_fetch_all_reviews(self) -> None:
        """Test case for fetch_all_reviews

        ReviewController@index
        """
        pass

    def test_fetch_reviews(self) -> None:
        """Test case for fetch_reviews

        ReviewController@show
        """
        pass


if __name__ == '__main__':
    unittest.main()
