# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model9b95892cc29cee3ccd11e3f92223224c200_response import Model9b95892cc29cee3ccd11e3f92223224c200Response

class TestModel9b95892cc29cee3ccd11e3f92223224c200Response(unittest.TestCase):
    """Model9b95892cc29cee3ccd11e3f92223224c200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model9b95892cc29cee3ccd11e3f92223224c200Response:
        """Test Model9b95892cc29cee3ccd11e3f92223224c200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model9b95892cc29cee3ccd11e3f92223224c200Response`
        """
        model = Model9b95892cc29cee3ccd11e3f92223224c200Response()
        if include_optional:
            return Model9b95892cc29cee3ccd11e3f92223224c200Response(
                current_page = 1,
                data = [
                    gateway_api_sdk.models._9b95892cc29cee3ccd11e3f92223224c_200_response_data_inner._9b95892cc29cee3ccd11e3f92223224c_200_response_data_inner(
                        _source = [
                            gateway_api_sdk.models._9b95892cc29cee3ccd11e3f92223224c_200_response_data_inner__source_inner._9b95892cc29cee3ccd11e3f92223224c_200_response_data_inner__source_inner(
                                id = '', 
                                name = '', 
                                img_url = '', 
                                dataset_titles = [
                                    null
                                    ], 
                                geographic_location = [
                                    null
                                    ], )
                            ], 
                        highlight = [
                            gateway_api_sdk.models._8db417727e7fe7c2e99206b060a3b882_200_response_data_inner_highlight_inner._8db417727e7fe7c2e99206b060a3b882_200_response_data_inner_highlight_inner(
                                lay_summary = [
                                    null
                                    ], )
                            ], )
                    ],
                first_page_url = 'http:\/\/localhost:8000\/api\/v1\/dur?page=1',
                var_from = 1,
                last_page = 1,
                last_page_url = 'http:\/\/localhost:8000\/api\/v1\/dur?page=1',
                links = [],
                next_page_url = 'null',
                path = 'http:\/\/localhost:8000\/api\/v1\/dur',
                per_page = 25,
                prev_page_url = 'null',
                to = 3,
                total = 3
            )
        else:
            return Model9b95892cc29cee3ccd11e3f92223224c200Response(
        )
        """

    def testModel9b95892cc29cee3ccd11e3f92223224c200Response(self):
        """Test Model9b95892cc29cee3ccd11e3f92223224c200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
