# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.fetch_team_dar_application_files200_response import FetchTeamDarApplicationFiles200Response

class TestFetchTeamDarApplicationFiles200Response(unittest.TestCase):
    """FetchTeamDarApplicationFiles200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchTeamDarApplicationFiles200Response:
        """Test FetchTeamDarApplicationFiles200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchTeamDarApplicationFiles200Response`
        """
        model = FetchTeamDarApplicationFiles200Response()
        if include_optional:
            return FetchTeamDarApplicationFiles200Response(
                message = '',
                data = gateway_api_sdk.models.fetch_team_dar_application_files_200_response_data.fetch_team_dar_application_files_200_response_data(
                    id = 123, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    filename = '', 
                    file_location = '', 
                    user_id = '', 
                    status = '', 
                    application_id = 56, 
                    question_id = 56, 
                    error = '', )
            )
        else:
            return FetchTeamDarApplicationFiles200Response(
        )
        """

    def testFetchTeamDarApplicationFiles200Response(self):
        """Test FetchTeamDarApplicationFiles200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
