# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.update_user_dar_application_request_answers_inner_answer import UpdateUserDarApplicationRequestAnswersInnerAnswer

class TestUpdateUserDarApplicationRequestAnswersInnerAnswer(unittest.TestCase):
    """UpdateUserDarApplicationRequestAnswersInnerAnswer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserDarApplicationRequestAnswersInnerAnswer:
        """Test UpdateUserDarApplicationRequestAnswersInnerAnswer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserDarApplicationRequestAnswersInnerAnswer`
        """
        model = UpdateUserDarApplicationRequestAnswersInnerAnswer()
        if include_optional:
            return UpdateUserDarApplicationRequestAnswersInnerAnswer(
                value = 'an answer'
            )
        else:
            return UpdateUserDarApplicationRequestAnswersInnerAnswer(
        )
        """

    def testUpdateUserDarApplicationRequestAnswersInnerAnswer(self):
        """Test UpdateUserDarApplicationRequestAnswersInnerAnswer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
