# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.api.admin_search_api import AdminSearchApi


class TestAdminSearchApi(unittest.TestCase):
    """AdminSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminSearchApi()

    def tearDown(self) -> None:
        pass

    def test_create_admin_search_reindex(self) -> None:
        """Test case for create_admin_search_reindex

        Queue a drop+recreate+import of a search entity's Typesense collection
        """
        pass

    def test_fetch_admin_search_status(self) -> None:
        """Test case for fetch_admin_search_status

        Get Typesense collection status for every onboarded search entity
        """
        pass

    def test_update_admin_search_feature(self) -> None:
        """Test case for update_admin_search_feature

        Activate or deactivate a search-related Pennant feature flag
        """
        pass


if __name__ == '__main__':
    unittest.main()
