# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model2935b32e38ac989b35eab8e0b7552cd3_request import Model2935b32e38ac989b35eab8e0b7552cd3Request

class TestModel2935b32e38ac989b35eab8e0b7552cd3Request(unittest.TestCase):
    """Model2935b32e38ac989b35eab8e0b7552cd3Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model2935b32e38ac989b35eab8e0b7552cd3Request:
        """Test Model2935b32e38ac989b35eab8e0b7552cd3Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model2935b32e38ac989b35eab8e0b7552cd3Request`
        """
        model = Model2935b32e38ac989b35eab8e0b7552cd3Request()
        if include_optional:
            return Model2935b32e38ac989b35eab8e0b7552cd3Request(
                name = 'Safe People',
                description = 'Who has access?',
                parent_section = 1,
                order = 1
            )
        else:
            return Model2935b32e38ac989b35eab8e0b7552cd3Request(
        )
        """

    def testModel2935b32e38ac989b35eab8e0b7552cd3Request(self):
        """Test Model2935b32e38ac989b35eab8e0b7552cd3Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
