# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.fetch_all_reviews200_response_data_inner import FetchAllReviews200ResponseDataInner

class TestFetchAllReviews200ResponseDataInner(unittest.TestCase):
    """FetchAllReviews200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchAllReviews200ResponseDataInner:
        """Test FetchAllReviews200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchAllReviews200ResponseDataInner`
        """
        model = FetchAllReviews200ResponseDataInner()
        if include_optional:
            return FetchAllReviews200ResponseDataInner(
                id = 1,
                tool_id = 1,
                user_id = 1,
                rating = 1,
                review_text = 'Laudantium fugit veniam iste.',
                review_state = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tool = gateway_api_sdk.models.fetch_all_reviews_200_response_data_inner_tool.fetch_all_reviews_200_response_data_inner_tool(
                    id = 1, 
                    mongo_object_id = 'ce37b00y7eiux03cca09pr0u', 
                    name = 'Vel id iure aut qui quia rerum.', 
                    url = 'https://www.dickens.com/maiores-a-qui-laborum-reiciendis-necessitatibus-sed-non', 
                    description = 'Sit quisquam est recusandae.', 
                    license = 'Inventore dolor quis magnam qui.', 
                    tech_stack = 'Inventore dolor quis magnam qui.', 
                    user_id = 1, 
                    enabled = False, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                user = gateway_api_sdk.models.fetch_all_reviews_200_response_data_inner_user.fetch_all_reviews_200_response_data_inner_user(
                    id = 1, 
                    name = 'Rocio Mayer', 
                    firstname = 'something or null', 
                    lastname = 'something or null', 
                    email = 'stanton.sibyl@example.net', 
                    email_verified_at = 56, 
                    providerid = 'something or null', 
                    provider = 'something or null', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return FetchAllReviews200ResponseDataInner(
        )
        """

    def testFetchAllReviews200ResponseDataInner(self):
        """Test FetchAllReviews200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
