# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.search_collections200_response import SearchCollections200Response

class TestSearchCollections200Response(unittest.TestCase):
    """SearchCollections200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchCollections200Response:
        """Test SearchCollections200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchCollections200Response`
        """
        model = SearchCollections200Response()
        if include_optional:
            return SearchCollections200Response(
                current_page = 1,
                data = [
                    gateway_api_sdk.models.search_collections_200_response_data_inner.search_collections_200_response_data_inner(
                        _source = [
                            gateway_api_sdk.models.search_collections_200_response_data_inner__source_inner.search_collections_200_response_data_inner__source_inner(
                                name = '', 
                                description = '', 
                                keywords = '', 
                                related_objects/keywords = '', 
                                related_objects/title = '', 
                                related_objects/name = '', 
                                related_objects/description = '', )
                            ], 
                        highlight = [
                            gateway_api_sdk.models.search_tools_200_response_data_inner_highlight_inner.search_tools_200_response_data_inner_highlight_inner(
                                description = [
                                    null
                                    ], )
                            ], )
                    ],
                first_page_url = 'http:\/\/localhost:8000\/api\/v1\/collections?page=1',
                var_from = 1,
                last_page = 1,
                last_page_url = 'http:\/\/localhost:8000\/api\/v1\/collections?page=1',
                links = [],
                next_page_url = 'null',
                path = 'http:\/\/localhost:8000\/api\/v1\/collections',
                per_page = 25,
                prev_page_url = 'null',
                to = 3,
                total = 3
            )
        else:
            return SearchCollections200Response(
        )
        """

    def testSearchCollections200Response(self):
        """Test SearchCollections200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
