# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.model234386e06c6b29d5aaca2ed8f89cb9aa200_response_data_inner import Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner

class TestModel234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner(unittest.TestCase):
    """Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner:
        """Test Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner`
        """
        model = Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner()
        if include_optional:
            return Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner(
                id = 123,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                team_id = 1,
                user_id = 1,
                published = True,
                locked = False
            )
        else:
            return Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner(
        )
        """

    def testModel234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner(self):
        """Test Model234386e06c6b29d5aaca2ed8f89cb9aa200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
