# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gateway_api_sdk.models.license import License

class TestLicense(unittest.TestCase):
    """License unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> License:
        """Test License
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `License`
        """
        model = License()
        if include_optional:
            return License(
                id = 1,
                code = 'HDR_CATEGORY_AVAILABLE_UPON_REQUEST',
                label = 'Available upon request',
                valid_since = '2024-04-15T00:00Z',
                valid_until = '2024-04-15T00:00Z',
                definition = 'Access to the software is available upon request.',
                verified = True,
                origin = 'HDR',
                created_at = '2024-01-15T10:30Z',
                updated_at = '2024-06-01T08:00Z',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return License(
        )
        """

    def testLicense(self):
        """Test License"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
