# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FetchApplications200ResponseDataInner(BaseModel):
    """
    FetchApplications200ResponseDataInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [123]})
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Voluptas incidunt repellat animi. Sed ut beatae fugit ullam."]})
    app_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["obmWCcsccdxH5iHgLTJDZNXNkyW1ZxZ3"]})
    client_id: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["w8CLyeP8vhnPK1V0mJ8ubU7UHCVnK7Bm"]})
    image_link: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["hhttps:\\/\\/via.placeholder.com\\/640x480.png\\/0044ee?text=animals+harum"]})
    description: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Magni minima facilis quo soluta. Ab quasi quaerat doloremque. Sapiente asperiores nisi maiores ex quia velit."]})
    team_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    user_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [2]})
    enabled: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    permissions: Optional[List[Any]] = Field(default=None, json_schema_extra={"examples": ["[]"]})
    team: Optional[List[Any]] = Field(default=None, json_schema_extra={"examples": ["[]"]})
    user: Optional[List[Any]] = Field(default=None, json_schema_extra={"examples": ["[]"]})
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "app_id", "client_id", "image_link", "description", "team_id", "user_id", "enabled", "permissions", "team", "user", "created_at", "updated_at", "deleted_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FetchApplications200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FetchApplications200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "app_id": obj.get("app_id"),
            "client_id": obj.get("client_id"),
            "image_link": obj.get("image_link"),
            "description": obj.get("description"),
            "team_id": obj.get("team_id"),
            "user_id": obj.get("user_id"),
            "enabled": obj.get("enabled"),
            "permissions": obj.get("permissions"),
            "team": obj.get("team"),
            "user": obj.get("user"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at")
        })
        return _obj


