# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Model17336ba551813e00975d3c2da09211c0200ResponseData(BaseModel):
    """
    Model17336ba551813e00975d3c2da09211c0200ResponseData
    """ # noqa: E501
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
    question_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    version: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    default: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    required: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    section_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    user_id: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    locked: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    archived: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    archived_date: Optional[datetime] = None
    force_required: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    allow_guidance_override: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    is_child: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [0]})
    question_type: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["STANDARD"]})
    title: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["This is a question"]})
    guidance: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["This is a question's guidance"]})
    options: Optional[List[Any]] = None
    component: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["RadioGroup"]})
    validations: Optional[List[Any]] = None
    __properties: ClassVar[List[str]] = ["created_at", "updated_at", "deleted_at", "question_id", "version", "default", "required", "section_id", "user_id", "locked", "archived", "archived_date", "force_required", "allow_guidance_override", "is_child", "question_type", "title", "guidance", "options", "component", "validations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Model17336ba551813e00975d3c2da09211c0200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Model17336ba551813e00975d3c2da09211c0200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "deleted_at": obj.get("deleted_at"),
            "question_id": obj.get("question_id"),
            "version": obj.get("version"),
            "default": obj.get("default"),
            "required": obj.get("required"),
            "section_id": obj.get("section_id"),
            "user_id": obj.get("user_id"),
            "locked": obj.get("locked"),
            "archived": obj.get("archived"),
            "archived_date": obj.get("archived_date"),
            "force_required": obj.get("force_required"),
            "allow_guidance_override": obj.get("allow_guidance_override"),
            "is_child": obj.get("is_child"),
            "question_type": obj.get("question_type"),
            "title": obj.get("title"),
            "guidance": obj.get("guidance"),
            "options": obj.get("options"),
            "component": obj.get("component"),
            "validations": obj.get("validations")
        })
        return _obj


