# coding: utf-8

"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateApplicationsRequest(BaseModel):
    """
    UpdateApplicationsRequest
    """ # noqa: E501
    name: StrictStr = Field(json_schema_extra={"examples": ["Corrupti in a voluptas. Eligendi saepe sed sit."]})
    image_link: StrictStr = Field(json_schema_extra={"examples": ["https://via.placeholder.com/640x480.png/0022dd?text=animals+aliquam"]})
    description: StrictStr = Field(json_schema_extra={"examples": ["Praesentium ut et quae suscipit ut quo adipisci. Enim ut tenetur ad omnis ut consequatur. "]})
    team_id: StrictInt = Field(json_schema_extra={"examples": [1]})
    user_id: StrictInt = Field(json_schema_extra={"examples": [2]})
    enabled: StrictBool = Field(json_schema_extra={"examples": [False]})
    permissions: List[Any] = Field(json_schema_extra={"examples": ["[]"]})
    notifications: Optional[List[Any]] = Field(default=None, json_schema_extra={"examples": ["[]"]})
    __properties: ClassVar[List[str]] = ["name", "image_link", "description", "team_id", "user_id", "enabled", "permissions", "notifications"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateApplicationsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateApplicationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "image_link": obj.get("image_link"),
            "description": obj.get("description"),
            "team_id": obj.get("team_id"),
            "user_id": obj.get("user_id"),
            "enabled": obj.get("enabled"),
            "permissions": obj.get("permissions"),
            "notifications": obj.get("notifications")
        })
        return _obj


