"""
    HDRUK Gateway API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from gateway_api_sdk.models.model9946399cbddb0dcadcbd5801e5ee1dd4200_response import Model9946399cbddb0dcadcbd5801e5ee1dd4200Response
from gateway_api_sdk.models.model9946399cbddb0dcadcbd5801e5ee1dd4_request import Model9946399cbddb0dcadcbd5801e5ee1dd4Request
from gateway_api_sdk.models.model9a0abfa6186327d43c51259d5b524fde200_response import Model9a0abfa6186327d43c51259d5b524fde200Response
from gateway_api_sdk.models.model9a0abfa6186327d43c51259d5b524fde_request import Model9a0abfa6186327d43c51259d5b524fdeRequest

from gateway_api_sdk.api_client import ApiClient, RequestSerialized
from gateway_api_sdk.api_response import ApiResponse
from gateway_api_sdk.rest import RESTResponseType


class SearchPublicationsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def call_9946399cbddb0dcadcbd5801e5ee1dd4(
        self,
        model9946399cbddb0dcadcbd5801e5ee1dd4_request: Annotated[Model9946399cbddb0dcadcbd5801e5ee1dd4Request, Field(description="Submit search query")],
        sort: Annotated[Optional[StrictStr], Field(description="Field to sort by (default: 'score')")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction ('asc' or 'desc', default: 'desc')")] = None,
        source: Annotated[Optional[StrictStr], Field(description="Which source to search ('GAT' or 'FED', default: 'GAT')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Model9946399cbddb0dcadcbd5801e5ee1dd4200Response:
        """Search@publications

        Returns gateway publications related to the provided query term(s)

        :param model9946399cbddb0dcadcbd5801e5ee1dd4_request: Submit search query (required)
        :type model9946399cbddb0dcadcbd5801e5ee1dd4_request: Model9946399cbddb0dcadcbd5801e5ee1dd4Request
        :param sort: Field to sort by (default: 'score')
        :type sort: str
        :param direction: Sort direction ('asc' or 'desc', default: 'desc')
        :type direction: str
        :param source: Which source to search ('GAT' or 'FED', default: 'GAT')
        :type source: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9946399cbddb0dcadcbd5801e5ee1dd4_serialize(
            model9946399cbddb0dcadcbd5801e5ee1dd4_request=model9946399cbddb0dcadcbd5801e5ee1dd4_request,
            sort=sort,
            direction=direction,
            source=source,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9946399cbddb0dcadcbd5801e5ee1dd4200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def call_9946399cbddb0dcadcbd5801e5ee1dd4_with_http_info(
        self,
        model9946399cbddb0dcadcbd5801e5ee1dd4_request: Annotated[Model9946399cbddb0dcadcbd5801e5ee1dd4Request, Field(description="Submit search query")],
        sort: Annotated[Optional[StrictStr], Field(description="Field to sort by (default: 'score')")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction ('asc' or 'desc', default: 'desc')")] = None,
        source: Annotated[Optional[StrictStr], Field(description="Which source to search ('GAT' or 'FED', default: 'GAT')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Model9946399cbddb0dcadcbd5801e5ee1dd4200Response]:
        """Search@publications

        Returns gateway publications related to the provided query term(s)

        :param model9946399cbddb0dcadcbd5801e5ee1dd4_request: Submit search query (required)
        :type model9946399cbddb0dcadcbd5801e5ee1dd4_request: Model9946399cbddb0dcadcbd5801e5ee1dd4Request
        :param sort: Field to sort by (default: 'score')
        :type sort: str
        :param direction: Sort direction ('asc' or 'desc', default: 'desc')
        :type direction: str
        :param source: Which source to search ('GAT' or 'FED', default: 'GAT')
        :type source: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9946399cbddb0dcadcbd5801e5ee1dd4_serialize(
            model9946399cbddb0dcadcbd5801e5ee1dd4_request=model9946399cbddb0dcadcbd5801e5ee1dd4_request,
            sort=sort,
            direction=direction,
            source=source,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9946399cbddb0dcadcbd5801e5ee1dd4200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def call_9946399cbddb0dcadcbd5801e5ee1dd4_without_preload_content(
        self,
        model9946399cbddb0dcadcbd5801e5ee1dd4_request: Annotated[Model9946399cbddb0dcadcbd5801e5ee1dd4Request, Field(description="Submit search query")],
        sort: Annotated[Optional[StrictStr], Field(description="Field to sort by (default: 'score')")] = None,
        direction: Annotated[Optional[StrictStr], Field(description="Sort direction ('asc' or 'desc', default: 'desc')")] = None,
        source: Annotated[Optional[StrictStr], Field(description="Which source to search ('GAT' or 'FED', default: 'GAT')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search@publications

        Returns gateway publications related to the provided query term(s)

        :param model9946399cbddb0dcadcbd5801e5ee1dd4_request: Submit search query (required)
        :type model9946399cbddb0dcadcbd5801e5ee1dd4_request: Model9946399cbddb0dcadcbd5801e5ee1dd4Request
        :param sort: Field to sort by (default: 'score')
        :type sort: str
        :param direction: Sort direction ('asc' or 'desc', default: 'desc')
        :type direction: str
        :param source: Which source to search ('GAT' or 'FED', default: 'GAT')
        :type source: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9946399cbddb0dcadcbd5801e5ee1dd4_serialize(
            model9946399cbddb0dcadcbd5801e5ee1dd4_request=model9946399cbddb0dcadcbd5801e5ee1dd4_request,
            sort=sort,
            direction=direction,
            source=source,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9946399cbddb0dcadcbd5801e5ee1dd4200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _call_9946399cbddb0dcadcbd5801e5ee1dd4_serialize(
        self,
        model9946399cbddb0dcadcbd5801e5ee1dd4_request,
        sort,
        direction,
        source,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if direction is not None:
            
            _query_params.append(('direction', direction))
            
        if source is not None:
            
            _query_params.append(('source', source))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if model9946399cbddb0dcadcbd5801e5ee1dd4_request is not None:
            _body_params = model9946399cbddb0dcadcbd5801e5ee1dd4_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/search/publications',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def call_9a0abfa6186327d43c51259d5b524fde(
        self,
        model9a0abfa6186327d43c51259d5b524fde_request: Annotated[Model9a0abfa6186327d43c51259d5b524fdeRequest, Field(description="Submit search query")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Model9a0abfa6186327d43c51259d5b524fde200Response:
        """Search@publications

        Returns publications from EuropePMC matching a give DOI

        :param model9a0abfa6186327d43c51259d5b524fde_request: Submit search query (required)
        :type model9a0abfa6186327d43c51259d5b524fde_request: Model9a0abfa6186327d43c51259d5b524fdeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9a0abfa6186327d43c51259d5b524fde_serialize(
            model9a0abfa6186327d43c51259d5b524fde_request=model9a0abfa6186327d43c51259d5b524fde_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9a0abfa6186327d43c51259d5b524fde200Response",
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def call_9a0abfa6186327d43c51259d5b524fde_with_http_info(
        self,
        model9a0abfa6186327d43c51259d5b524fde_request: Annotated[Model9a0abfa6186327d43c51259d5b524fdeRequest, Field(description="Submit search query")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Model9a0abfa6186327d43c51259d5b524fde200Response]:
        """Search@publications

        Returns publications from EuropePMC matching a give DOI

        :param model9a0abfa6186327d43c51259d5b524fde_request: Submit search query (required)
        :type model9a0abfa6186327d43c51259d5b524fde_request: Model9a0abfa6186327d43c51259d5b524fdeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9a0abfa6186327d43c51259d5b524fde_serialize(
            model9a0abfa6186327d43c51259d5b524fde_request=model9a0abfa6186327d43c51259d5b524fde_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9a0abfa6186327d43c51259d5b524fde200Response",
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def call_9a0abfa6186327d43c51259d5b524fde_without_preload_content(
        self,
        model9a0abfa6186327d43c51259d5b524fde_request: Annotated[Model9a0abfa6186327d43c51259d5b524fdeRequest, Field(description="Submit search query")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Search@publications

        Returns publications from EuropePMC matching a give DOI

        :param model9a0abfa6186327d43c51259d5b524fde_request: Submit search query (required)
        :type model9a0abfa6186327d43c51259d5b524fde_request: Model9a0abfa6186327d43c51259d5b524fdeRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._call_9a0abfa6186327d43c51259d5b524fde_serialize(
            model9a0abfa6186327d43c51259d5b524fde_request=model9a0abfa6186327d43c51259d5b524fde_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Model9a0abfa6186327d43c51259d5b524fde200Response",
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _call_9a0abfa6186327d43c51259d5b524fde_serialize(
        self,
        model9a0abfa6186327d43c51259d5b524fde_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if model9a0abfa6186327d43c51259d5b524fde_request is not None:
            _body_params = model9a0abfa6186327d43c51259d5b524fde_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/search/doi',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


